// flow-typed signature: 2c6b2cf28232c70b367aae423324e929
// flow-typed version: <<STUB>>/eslint-plugin-json_v^1.4.0/flow_v0.99.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-json'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-json' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-json/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-json/lib/index.js' {
  declare module.exports: $Exports<'eslint-plugin-json/lib/index'>;
}
