// flow-typed signature: 6f9b7ad03a9f9ffda8f3c19ca5c3c96e
// flow-typed version: <<STUB>>/eslint-plugin-flow-header_v^0.2.0/flow_v0.118.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-flow-header'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-flow-header' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-flow-header/lib' {
  declare module.exports: any;
}

declare module 'eslint-plugin-flow-header/lib/rules/flow-header' {
  declare module.exports: any;
}

declare module 'eslint-plugin-flow-header/tests/lib/rules/flow-header' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-flow-header/lib/index' {
  declare module.exports: $Exports<'eslint-plugin-flow-header/lib'>;
}
declare module 'eslint-plugin-flow-header/lib/index.js' {
  declare module.exports: $Exports<'eslint-plugin-flow-header/lib'>;
}
declare module 'eslint-plugin-flow-header/lib/rules/flow-header.js' {
  declare module.exports: $Exports<'eslint-plugin-flow-header/lib/rules/flow-header'>;
}
declare module 'eslint-plugin-flow-header/tests/lib/rules/flow-header.js' {
  declare module.exports: $Exports<'eslint-plugin-flow-header/tests/lib/rules/flow-header'>;
}
